apiVersion: v1
kind: Service
metadata:
  name: antaeus
  namespace: antaeus
  labels:
    app: antaeus
spec:
  type: LoadBalancer
  selector:
    app: antaeus
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000