apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: payment
  labels:
    app: payment
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080